### ISSUE TITLE
Independent PPO 算法中Actor loss计算问题

### ISSUE THREAD

**Issue by huang312** [yangchen1997/Multi-Agent-Reinforcement-Learning#13]
您好，我在阅读ippo算法的代码时，有一些地方没看懂，有几个问题想请教一下

1.在Independent PPO算法中计算Actor网络的loss中，我理解的是把每个agent的loss加起来算一个平均值，请问为什么要这样计算呢？
```
curr_log_probs = []
curr_state_values = []
# 这里在一次更新中使用了每个agent采样的数据来计算loss
for agent_num in range(self.n_agents):
    one_action_mean, self.rnn_hidden[i] = self.ppo_actor(obs[:, i], self.rnn_hidden[i])
    curr_state_value = self.ppo_critic(obs[:, i])
    dist = MultivariateNormal(one_action_mean, self.cov_mat)
    curr_log_prob = dist.log_prob(actions[:, i])
    curr_log_probs.append(curr_log_prob)
    curr_state_values.append(curr_state_value)
curr_log_probs = torch.stack(curr_log_probs, dim=1)
curr_state_values = torch.stack(curr_state_values, dim=0)
```
我看到有一些其他的ippo实现中，每个agent采样的数据分别保存在自己的replay buffer中，然后每次策略更新时只使用一个agent采样到的数据更新，请问这两种方式有区别吗？

2.ippo网络结构中rnn网络的使用
```
one_action_mean, self.rnn_hidden[i] = self.ppo_actor(obs[:, i], self.rnn_hidden[i])
```
在上面的代码中，我理解self.rnn_hidden[i]这个向量每次更新时只使用了一次，那是不是这样写也可以：
```
one_action_mean, _ = self.ppo_actor(obs[:, i], self.rnn_hidden[i])
```
而且我注意到每次self.rnn_hidden[i]都初始化为全零，那是不是给actor网络传入一个全零向量就可以了？

**Comment by yangchen1997** [comment]
1、我觉得是两种不同的实现方式，我使用的方式是把所有agent的critic值叠加在一起，然后与真实的state值计算MSEloss。这个过程中会在计算loss之后取均值
2、replay buffer我在其他算法中也有实现，我了解到ippo是一种on policy算法，即学习时使用当前的策略网络输出的结果。replay buffer在off policy算法中使用，用于保存之前几次策略网络的结果。
3、self.rnn_hidden初始值是全零向量。它是实时更新的，每次训练时都会刷新为self.ppo_actor返回的rnn_hidden（具体参考rnn的结构和原理）
