### ISSUE TITLE
您好

### ISSUE THREAD

**Issue by yyds-xtt** [yangchen1997/Multi-Agent-Reinforcement-Learning#2]
Grid-Wise Control for Multi-Agent Reinforcement Learning in Video Game AI  这个是这个论文的代码吗

**Comment by yangchen1997** [comment]
> Grid-Wise Control for Multi-Agent Reinforcement Learning in Video Game AI 这个是这个论文的代码吗

您好，是这个论文的代码。但是我还有一些没有写完。

**Comment by yyds-xtt** [comment]
thank you

**Comment by yangchen1997** [comment]
> thank you

没关系的，也欢迎跟我通过邮件交流。

**Comment by yyds-xtt** [comment]
这个论文的代码，还没有开源是吧



---原始邮件---
发件人: "Chen ***@***.***&gt;
发送时间: 2022年4月23日(周六) 上午9:11
收件人: ***@***.***&gt;;
抄送: "NEU RL ***@***.******@***.***&gt;;
主题: Re: [yangchen1997/marl] 您好 (Issue #2)




  
thank you
  
没关系的，也欢迎跟我通过邮件交流。

**Comment by yangchen1997** [comment]
是的这个论文的代码还没开源



---原始邮件---
发件人: "NEU RL ***@***.***&gt;
发送时间: 2022年4月23日(周六) 上午9:12
收件人: ***@***.***&gt;;
抄送: "Chen ***@***.******@***.***&gt;;
主题: Re: [yangchen1997/marl] 您好 (Issue #2)




 这个论文的代码，还没有开源是吧 
 
 
 
 ---原始邮件--- 
 发件人: "Chen ***@***.***&amp;gt; 
 发送时间: 2022年4月23日(周六) 上午9:11 
 收件人: ***@***.***&amp;gt;; 
 抄送: "NEU RL ***@***.******@***.***&amp;gt;; 
 主题: Re: [yangchen1997/marl] 您好 (Issue #2) 
 
 
 
 
    
 thank you 
    
 没关系的，也欢迎跟我通过邮件交流。

**Comment by yangchen1997** [comment]
> 这个论文的代码，还没有开源是吧
> […](#)
> ---原始邮件--- 发件人: "Chen ***@***.***&gt; 发送时间: 2022年4月23日(周六) 上午9:11 收件人: ***@***.***&gt;; 抄送: "NEU RL ***@***.******@***.***&gt;; 主题: Re: [yangchen1997/marl] 您好 (Issue #2) thank you 没关系的，也欢迎跟我通过邮件交流。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

我也是按照自己的想法来复现的，可能有的地方跟作者的思路不太一样。有问题的话也欢迎指正和交流，谢谢。

**Comment by yangchen1997** [comment]
finish

**Comment by yyds-xtt** [comment]
thank you

**Comment by yyds-xtt** [comment]
好



---原始邮件---
发件人: "Chen ***@***.***&gt;
发送时间: 2022年4月23日(周六) 上午9:44
收件人: ***@***.***&gt;;
抄送: "NEU RL ***@***.******@***.***&gt;;
主题: Re: [yangchen1997/marl] 您好 (Issue #2)




  
这个论文的代码，还没有开源是吧
 …
 ---原始邮件--- 发件人: "Chen @.&gt; 发送时间: 2022年4月23日(周六) 上午9:11 收件人: @.&gt;; 抄送: "NEU RL @.@.&gt;; 主题: Re: [yangchen1997/marl] 您好 (Issue #2) thank you 没关系的，也欢迎跟我通过邮件交流。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
我也是按照自己的想法来复现的，可能有的地方跟作者的思路不太一样。有问题的话也欢迎指正和交流，谢谢。

**Comment by yyds-xtt** [comment]
这个没有开源是吧



---原始邮件---
发件人: "Chen ***@***.***&gt;
发送时间: 2022年4月23日(周六) 上午9:11
收件人: ***@***.***&gt;;
抄送: "NEU RL ***@***.******@***.***&gt;;
主题: Re: [yangchen1997/marl] 您好 (Issue #2)




  
thank you
  
没关系的，也欢迎跟我通过邮件交流。

**Comment by yangchen1997** [comment]
> 
对，这个论文的代码还没有开源
