### ISSUE TITLE
请问有运行结果吗？

### ISSUE THREAD

**Issue by zerlinwang** [yangchen1997/Multi-Agent-Reinforcement-Learning#8]
谢谢作者的实现，很有帮助！
我这边也实现了相关算法在pettingzoo的simple_spread_v2的代码，最后能收敛到 -800 分左右。
max_cycle = 100
n_agents = 3
local_ratio = 0.5
最后收敛到-800左右，您这边有运行的结果吗，想和您对一下，看看算法实现和环境是否有问题。

**Comment by yangchen1997** [comment]
实在不好意思，我之前的图像找不到了，我使用的超参数是max_cycle = 80、n_agents = 3、local_ratio = 0.8，收敛大概是-500分左右，不同算法可能会有100左右分的偏差，另外您的 -800 这个结果是平均奖励吗，还是3个agent的奖励之和呐？我觉得最终结果可能跟几个因素有关: 环境, 算法, 迭代次数。希望能帮到您。

**Comment by zerlinwang** [comment]
> 实在不好意思，我之前的图像找不到了，我使用的超参数是max_cycle = 80、n_agents = 3、local_ratio = 0.8，收敛大概是-500分左右，不同算法可能会有100左右分的偏差，另外您的 -800 这个结果是平均奖励吗，还是3个agent的奖励之和呐？我觉得最终结果可能跟几个因素有关: 环境, 算法, 迭代次数。希望能帮到您。

感谢你的回复，我这边是所有智能体的总和奖励，如果是平均的话，大概在-300左右。我准备按照您的配置也跑跑看看

**Comment by zerlinwang** [comment]
> 实在不好意思，我之前的图像找不到了，我使用的超参数是max_cycle = 80、n_agents = 3、local_ratio = 0.8，收敛大概是-500分左右，不同算法可能会有100左右分的偏差，另外您的 -800 这个结果是平均奖励吗，还是3个agent的奖励之和呐？我觉得最终结果可能跟几个因素有关: 环境, 算法, 迭代次数。希望能帮到您。

-500分是智能体平均吗，我看到您的代码是平均奖励

**Comment by yangchen1997** [comment]
您好，我的-500是总体奖励。这个是之前做实验的数据，后来我修改了智能体的数量就使用了平均奖励。这个环境的参数对奖励影响还是挺大的，如果您想做对比实验，我建议横向对比(就是将这几个算法，在相同参数的环境下跑)。

**Comment by zerlinwang** [comment]
感谢作者的回复！
